Make the controller property in MobileSharedApplication be weak so that it doesn't retain forever
dropbox/SwiftyDropbox pull request #311
Opened 2021-04-12 20:35 UTC by YufeiG

MobileSharedApplication is a singleton.
This may require a major update as it is changing behavior that isn't backwards compatible. However I can't see this breaking anything for others because the controller should be held strongly in the view hierarchy.

Addresses https://github.com/dropbox/SwiftyDropbox/issues/294

2021-04-14 23:57 UTC, xuyanke commented
lgtm

2021-04-15 01:12 UTC, xuyanke approved these changes

2021-04-15 01:16 UTC, xuyanke requested changes
I guess we want to update OauthDesktop.swift too for this? https://github.com/dropbox/SwiftyDropbox/blob/master/Source/SwiftyDropbox/Platform/SwiftyDropbox_macOS/OAuthDesktop.swift#L89

2021-04-15 19:03 UTC, YufeiG commented
good catch

2021-04-15 22:32 UTC, xuyanke approved these changes

2021-04-15 22:37 UTC, merged